name: CI Build

on:
  push:
    branches: [ feature/custom ]
  pull_request:
    branches: [ feature/custom ]

jobs:
  macos-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13-arm64]
        arch: [x64, arm64]
        include:
          - os: macos-13-arm64
    name: macOS ${{ matrix.os }} (${{ matrix.arch }})

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          architecture: ${{ matrix.arch }}

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        env:
          GYP_ARGS: ${{ matrix.arch == 'arm64' && '--target_arch=arm64' || '' }}
        run: |
          ./node_modules/.bin/node-pre-gyp rebuild

      - name: Run tests
        run: npm test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.arch }}-build
          path: |
            ./build/
            ./lib/binding/

      - name: Upload Release Asset
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/Release/node_sqlite3.node
          asset_name: node_sqlite3-${{ runner.os }}-${{ matrix.arch }}.node
          asset_content_type: application/octet-stream
