name: CI Build

on:
  push:
    branches: [ feature/custom ]
  pull_request:
    branches: [ feature/custom ]

jobs:
  
  macos-x64-build:
    runs-on: macos-13
    name: macOS x64 Build

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          architecture: x64

      - name: Prepare OpenSSL for x64
        run: |
          lipo -thin x86_64 deps/openssl-macos/libcrypto.a -output deps/openssl-macos/libcrypto-thin.a
          mv deps/openssl-macos/libcrypto-thin.a deps/openssl-macos/libcrypto.a

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: |
          ./node_modules/.bin/node-pre-gyp rebuild

      - name: Run tests
        run: npm test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-x64-build
          path: |
            ./build/
            ./lib/binding/

  macos-arm64-build:
    runs-on: macos-13-arm64
    name: macOS arm64 Build

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          architecture: arm64

      - name: Prepare OpenSSL for arm64
        run: |
          lipo -thin arm64 deps/openssl-macos/libcrypto.a -output deps/openssl-macos/libcrypto-thin.a
          mv deps/openssl-macos/libcrypto-thin.a deps/openssl-macos/libcrypto.a

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        env:
          GYP_ARGS: --target_arch=arm64
        run: |
          ./node_modules/.bin/node-pre-gyp rebuild

      - name: Run tests
        run: npm test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-build
          path: |
            ./build/
            ./lib/binding/

      - name: Upload Release Asset
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/Release/node_sqlite3.node
          asset_name: node_sqlite3-${{ runner.os }}-${{ matrix.arch }}.node
          asset_content_type: application/octet-stream
